FROM ubuntu:16.04

CMD ["echo", "hello world"]

# Usage example
# docker build -t hello .
# docker run hello

# Publish to repository:
# docker tag hello peteruithoven/hello:0.0.1
# docker push peteruithoven/hello:0.0.1
# Remove locally
# docker rmi hello peteruithoven/hello:0.0.1
# Run from repository
# docker run peteruithoven/hello:0.0.1
